[project]
name = "lie-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "empath>=0.89",
    "joblib>=1.5.3",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "praat-parselmouth>=0.4.7",
    "scikit-learn>=1.8.0",
    "webrtcvad>=2.0.10",
]


